### PR TITLE
Readd MCForge

### PR DESCRIPTION
**Pull request by Asbestosstar**
I have added MC Forge back. It works on my MBP when running client with ./gradlew Client via the command line. NeoForge and FabricMC continue to work fine with ./gradlew runClient
Small changes needed to be made to support MC Forge, mainly the readding of the removed contents.

### CODE REVIEW

**Comment by Witixin1512** [comment]
I'm against this, given your PR crashes in Production since Mixins do not work in Forge 1.20.6. Jar in Jar has also been broken in Forge 1.20.6 if I remember correctly. 

In my opinion, this template should not support something that does not function correctly.

**Comment by Asbestosstar** [comment]
In that case this can just be delayed until Forge finally gets Mixin 0.8.6  or 0.8.7 which will support it, in this PR so far i modified it to be J17 and did work on my system, but Forge are in the process of getting with Mixin 0.8.6+ meaning soon that this will support J21, so if that is a priority we can wait. About the JiJ situation, I think it does kinda work but could maybe be fragil.

**Comment by PaintNinja** [comment]
> I'm against this, given your PR crashes in Production since Mixins do not work in Forge 1.20.6. Jar in Jar has also been broken in Forge 1.20.6 if I remember correctly.

Forge has received no reports of either of the issues you're referring to. Looking at the PR, the cause of the crashes are due to mistakes @Asbestosstar has made - namely not accounting for Forge now using runtime MojMaps. Remapping needs to be turned off, refmaps removed, etc...

**Comment by jaredlll08** [comment]
Seeing that everyone who has commented on this issue has acknowledged that this PR itself has issues, I am going to be closing this PR.

**Pull request closed without merging**
