### PR TITLE
Added support for Kotlin DSL / 1.20.4

### PR DESCRIPTION
**Pull request by AlgorithmLX**
# Warning: Accept this PR after creating the "1.20.4-with-kotlin-dsl" branch!

I understand that this may not be very useful, but for some who want to use KDSL, it mb useful, and you will not have to rewrite from 1.18.2 to 1.20.4

### CODE REVIEW

**Comment by jaredlll08** [comment]
Should the `1.20.4-with-kotlin-dsl` branch be based off of `1.18-with-kotlin-dsl` or the `1.20.4` branch?

**Comment by AlgorithmLX** [comment]
The branch is based of `1.20.4`

**Comment by jaredlll08** [comment]
Thanks!

**Comment by AlgorithmLX** [comment]
> Thanks

Glad to help!

**Pull request merged**
