### PR TITLE
[1.18.2] Updates Gradle/Forge FG version/Fabric Loom

### PR DESCRIPTION
**Pull request by AzureDoom**
The same as PR #62 but for 1.18.2 as well, since this version is affected and may be used by new modders who want to do this version.

### CODE REVIEW

**Comment by jaredlll08** [comment]
Just to confirm this is tested to work?

Also can you actually update loom to `1.7`, it was released a few days ago

**Comment by AzureDoom** [comment]
Yes, I tested to ensure it built correctly but I'll bump that Loom version and reset to be safe for both this and #62

**Comment by AzureDoom** [comment]
Both have been bumped and gave me no issues!

**Comment by jaredlll08** [comment]
Thanks!

**Pull request merged**
